# Generated by Django 5.2.6 on 2025-10-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0002_auto_20250927_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerlink',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='footersection',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
